PRICE_COLUMNS = [
    "source_file",
    "source_path",
    "source_type",
    "source_role",
    "source_profile",
    "import_batch_id",
    "supplier",
    "price_basis",
    "currency",
    "version",
    "effective_date",
    "product_code",
    "product_name",
    "collection",
    "section",
    "tier",
    "cover_range",
    "cover_type",
    "size",
    "size_raw",
    "price",
    "raw_price",
    "formula",
    "page",
    "table_index",
    "row_index",
    "confidence",
    "needs_review",
    "review_reason",
    "lookup_key",
]


EXPORT_PRICE_COLUMNS = [
    ("Product Code", "product_code"),
    ("Product Name", "product_name"),
    ("Supplier", "supplier"),
    ("Version", "version"),
    ("Price Basis", "price_basis"),
    ("Currency", "currency"),
    ("Section", "section"),
    ("Tier", "tier"),
    ("Cover Range", "cover_range"),
    ("Cover Type", "cover_type"),
    ("Size", "size"),
    ("Price", "price"),
    ("Source File", "source_file"),
    ("Page", "page"),
    ("Lookup Key", "lookup_key"),
    ("Needs Review", "needs_review"),
    ("Review Reason", "review_reason"),
]
